### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by artgod1** [datahaven-net/amazon-easy-invoice#11]
$ sh invoices.sh 
Starting to download your invoices.
  File "download_invoices.py", line 84
    raise Exception(f"Product page could not be loaded.")
                                                       ^
SyntaxError: invalid syntax
You can find your invoices in Downloads folder in the project folder.

Any solutions?
Thanks

**Comment by vesellov** [comment]
Hi @artgod1 !
you probably run with python2.7 ?

this script only runs on python3.4 and higher i think...
